language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
services:
  - memcached
  - mysql
#  - postgresql
#addons:
#  postgresql: "9.4"
env:
  matrix:
    - DB=MySQLi
    - DB=SQLite
#    - DB=PostgreSQL

matrix:
  fast_finish: true
  include:
    - php: hhvm-nightly
      sudo: true
      dist: trusty
      group: edge # use until the next Travis Image update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      env: DB=MySQLi
    - php: hhvm-nightly
      sudo: true
      dist: trusty
      group: edge # use until the next Travis Image update
      env: DB=SQLite
  allow_failures:
    - php: nightly
#    - env: DB=PostgreSQL

before_script:
  - |
    if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then
      mysql -u root -e 'CREATE DATABASE `travis`;'
    fi
  - |
    if [[ $TRAVIS_PHP_VERSION = hhv* && $DB = 'MySQLi' ]]; then
      mysql -u root -e "CREATE USER 'travis'@'127.0.0.1' IDENTIFIED WITH mysql_native_password;"
      mysql -u root -e "GRANT ALL ON travis.* TO 'travis'@'%';"
      mysql -u root -e "DROP TABLE travis.test;"
    fi
  - |
    if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then
      echo yes | pecl install apcu-4.0.11
    fi
  - |
    if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then
      echo yes | pecl install apcu-5.1.6
    fi
  - |
    if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then
      echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi

# Only compute code coverage on PHP 7.0
# HHVM doesn't have write support for Phar archives, so we'll only run quick tests on it
script:
  - |
    if [[ $TRAVIS_PHP_VERSION != '7.0' ]]; then
      export SKIP_COVERAGE=1
    fi
  - |
    if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then
      # hhvm phpt-tests-runner tests/quick
      hhvm --php -d variables_order=EGPCS phpt-tests-runner tests
    else
      php -d variables_order=EGPCS phpt-tests-runner tests
    fi

after_success:
  - |
    if [[ $TRAVIS_PHP_VERSION = '7.0' && $DB = 'SQLite' ]]; then
      timeout 120 php -d variables_order=EGPCS -d phar.readonly=Off ci/upload_build.php
    fi

after_script:
  - |
    if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then
      php tests/code_coverage_report.php
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover tests/code_coverage_report/clover.xml
    fi
